"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const { Router } = require('express');
const router = Router();
const { obtenerUsuarios, buscarUsuario, eliminarUsuario, cambiarNombreUsuario, cambiarCorreo, cambiarContrasena, iniciarSesion, crearCuenta } = require('../controllers/usuarios');
const middlewares_1 = require("../controllers/middlewares");
router.get('/api/usuarios', middlewares_1.verifyToken, obtenerUsuarios);
router.post('/api/usuarios', middlewares_1.verifyToken, buscarUsuario);
router.delete('/api/usuarios', middlewares_1.verifyToken, eliminarUsuario);
router.post('/api/cambiarNombre', middlewares_1.verifyToken, cambiarNombreUsuario);
router.post('/api/cambiarCorreo', middlewares_1.verifyToken, cambiarCorreo);
router.post('/api/cambiarContrasenia', middlewares_1.verifyToken, cambiarContrasena);
router.post('/api/login', iniciarSesion);
router.post('/api/registro', crearCuenta);
module.exports = router;
